# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-11-28 21:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.IntegerField(blank=True, null=True)),
                ('purchasedService', models.CharField(max_length=50)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(default='In Progress', max_length=50)),
                ('createdDate', models.DateTimeField(auto_now_add=True)),
                ('lastUpdatedDate', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'Orders',
                'managed': False,
            },
        )
    ]
