# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-11-28 21:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_contact_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.IntegerField(blank=True, null=True)),
                ('email', models.EmailField(max_length=50)),
                ('reason', models.CharField(max_length=50)),
                ('messsage', models.CharField(max_length=50)),
                ('createdDate', models.DateTimeField(auto_now_add=True)),
                ('lastUpdatedDate', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
